- name: Build Switch configuration
  hosts: FABRIC
  connection: local
  gather_facts: false
  collections:
    - arista.avd

  tasks:

    - name: Generate AVD intended variables
      ansible.builtin.import_role:
        name: eos_designs

    - name: Generate device intended config and documentation
      ansible.builtin.import_role:
        name: eos_cli_config_gen

    - name: Generate ACT Topology
      ansible.builtin.import_role:
        name: act_topology_gen
      vars:
        connected_endpoints: true
        non_fabric_nodes: "{{ hostvars[inventory_hostname]['non_fabric_nodes'] }}"
