type: l3spine

mgmt_gateway: 192.168.3.1


csc_cloud_gateway:

    # Daemon Name
  - name: AristaCloudGateway

    # command to run as a daemon
    exec: /usr/bin/acg
    enabled: true
    option: [AGNI_API_TOKEN, "agni_token_core"]
