dhcp_servers:
  - disabled: false
    dns_servers_ipv4: [ 8.8.8.8 ]
    vrf: default
    subnets:
      - subnet: 192.168.3.0/24
        name: local
        default_gateway: 192.168.3.1
        ranges:
          - start: 192.168.3.50
            end: 192.168.3.250
      - subnet: 192.168.101.0/24
        name: TOLA_ATD_01
        default_gateway: 192.168.101.1
        ranges:
          - start: 192.168.101.100
            end: 192.168.101.150
      - subnet: 192.168.102.0/24
        name: TOLA_ATD_02
        default_gateway: 192.168.102.1
        ranges:
          - start: 192.168.102.100
            end: 192.168.102.150
      - subnet: 192.168.103.0/24
        name: TOLA_ATD_03
        default_gateway: 192.168.103.1
        ranges:
          - start: 192.168.103.100
            end: 192.168.103.150
      - subnet: 192.168.104.0/24
        name: TOLA_ATD_04
        default_gateway: 192.168.104.1
        ranges:
          - start: 192.168.104.100
            end: 192.168.104.150
      - subnet: 192.168.105.0/24
        name: TOLA_ATD_05
        default_gateway: 192.168.105.1
        ranges:
          - start: 192.168.105.100
            end: 192.168.105.150
      - subnet: 192.168.106.0/24
        name: TOLA_ATD_06
        default_gateway: 192.168.106.1
        ranges:
          - start: 192.168.106.100
            end: 192.168.106.150
      - subnet: 192.168.107.0/24
        name: TOLA_ATD_07
        default_gateway: 192.168.107.1
        ranges:
          - start: 192.168.107.100
            end: 192.168.107.150
      - subnet: 192.168.108.0/24
        name: TOLA_ATD_08
        default_gateway: 192.168.108.1
        ranges:
          - start: 192.168.108.100
            end: 192.168.108.150
      - subnet: 192.168.109.0/24
        name: TOLA_ATD_09
        default_gateway: 192.168.109.1
        ranges:
          - start: 192.168.109.100
            end: 192.168.109.150
      - subnet: 192.168.110.0/24
        name: TOLA_ATD_10
        default_gateway: 192.168.110.1
        ranges:
          - start: 192.168.110.100
            end: 192.168.110.150
      - subnet: 192.168.111.0/24
        name: TOLA_ATD_11
        default_gateway: 192.168.111.1
        ranges:
          - start: 192.168.111.100
            end: 192.168.111.150
      - subnet: 192.168.112.0/24
        name: TOLA_ATD_12
        default_gateway: 192.168.112.1
        ranges:
          - start: 192.168.112.100
            end: 192.168.112.150
      - subnet: 192.168.113.0/24
        name: TOLA_ATD_13
        default_gateway: 192.168.113.1
        ranges:
          - start: 192.168.113.100
            end: 192.168.113.150
      - subnet: 192.168.114.0/24
        name: TOLA_ATD_14
        default_gateway: 192.168.114.1
        ranges:
          - start: 192.168.114.100
            end: 192.168.114.150
      - subnet: 192.168.115.0/24
        name: TOLA_ATD_15
        default_gateway: 192.168.115.1
        ranges:
          - start: 192.168.115.100
            end: 192.168.115.150
      - subnet: 192.168.116.0/24
        name: TOLA_ATD_16
        default_gateway: 192.168.116.1
        ranges:
          - start: 192.168.116.100
            end: 192.168.116.150
      - subnet: 192.168.117.0/24
        name: TOLA_ATD_17
        default_gateway: 192.168.117.1
        ranges:
          - start: 192.168.117.100
            end: 192.168.117.150
      - subnet: 192.168.118.0/24
        name: TOLA_ATD_18
        default_gateway: 192.168.118.1
        ranges:
          - start: 192.168.118.100
            end: 192.168.118.150
      - subnet: 192.168.119.0/24
        name: TOLA_ATD_19
        default_gateway: 192.168.119.1
        ranges:
          - start: 192.168.119.100
            end: 192.168.119.150
      - subnet: 192.168.120.0/24
        name: TOLA_ATD_20
        default_gateway: 192.168.120.1
        ranges:
          - start: 192.168.120.100
            end: 192.168.120.150