
svi_profiles:
  - profile: leaf
    enabled: true
    raw_eos_cli: |
      dhcp server ipv4
    
tenants:
  - name: lab
    vrfs:
      - name: default
        svis:
          - id: 101
            name: TOLA_ATD_01
            description: "*** ATD LAB 01 VLAN ***"
            ip_address: "192.168.101.1/24"
            profile: leaf
          - id: 102
            name: TOLA_ATD_02
            description: "*** ATD LAB 02 VLAN ***"
            ip_address: "192.168.102.1/24"
            profile: leaf
          - id: 103
            name: TOLA_ATD_03
            description: "*** ATD LAB 03 VLAN ***"
            ip_address: "192.168.103.1/24"
            profile: leaf
          - id: 104
            name: TOLA_ATD_04
            description: "*** ATD LAB 04 VLAN ***"
            ip_address: "192.168.104.1/24"
            profile: leaf
          - id: 105
            name: TOLA_ATD_05
            description: "*** ATD LAB 05 VLAN ***"
            ip_address: "192.168.105.1/24"
            profile: leaf
          - id: 106
            name: TOLA_ATD_06
            description: "*** ATD LAB 06 VLAN ***"
            ip_address: "192.168.106.1/24"
            profile: leaf
          - id: 107
            name: TOLA_ATD_07
            description: "*** ATD LAB 07 VLAN ***"
            ip_address: "192.168.107.1/24"
            profile: leaf
          - id: 108
            name: TOLA_ATD_08
            description: "*** ATD L8AB 08 VLAN ***"
            ip_address: "192.168.108.1/24"
            profile: leaf
          - id: 109
            name: TOLA_ATD_09
            description: "*** ATD LAB 09 VLAN ***"
            ip_address: "192.168.109.1/24"
            profile: leaf
          - id: 110
            name: TOLA_ATD_10
            description: "*** ATD LAB 10 VLAN ***"
            ip_address: "192.168.110.1/24"
            profile: leaf
          - id: 111
            name: TOLA_ATD_11
            description: "*** ATD LAB 11 VLAN ***"
            ip_address: "192.168.111.1/24"
            profile: leaf
          - id: 112
            name: TOLA_ATD_12
            description: "*** ATD LAB 12 VLAN ***"
            ip_address: "192.168.112.1/24"
            profile: leaf
          - id: 113
            name: TOLA_ATD_13
            description: "*** ATD LAB 13 VLAN ***"
            ip_address: "192.168.113.1/24"
            profile: leaf
          - id: 114
            name: TOLA_ATD_14
            description: "*** ATD LAB 14 VLAN ***"
            ip_address: "192.168.114.1/24"
            profile: leaf
          - id: 115
            name: TOLA_ATD_15
            description: "*** ATD LAB 15 VLAN ***"
            ip_address: "192.168.115.1/24"
            profile: leaf
          - id: 116
            name: TOLA_ATD_16
            description: "*** ATD LAB 16 VLAN ***"
            ip_address: "192.168.116.1/24"
            profile: leaf
          - id: 117
            name: TOLA_ATD_17
            description: "*** ATD LAB 17 VLAN ***"
            ip_address: "192.168.117.1/24"
            profile: leaf
          - id: 118
            name: TOLA_ATD_18
            description: "*** ATD L8AB 18 VLAN ***"
            ip_address: "192.168.118.1/24"
            profile: leaf
          - id: 119
            name: TOLA_ATD_19
            description: "*** ATD LAB 19 VLAN ***"
            ip_address: "192.168.119.1/24"
            profile: leaf
          - id: 120
            name: TOLA_ATD_20
            description: "*** ATD LAB 20 VLAN ***"
            ip_address: "192.168.120.1/24"
            profile: leaf
          - id: 124
            name: TOLA_ATD_INSTRUCTOR
            description: "*** INSTRUCTOR LAB 24 VLAN ***"
            ip_address: "192.168.124.1/24"
            profile: leaf