
monitor_connectivity:
  shutdown: false
  interface_sets:
    - name: CM-Interfaces
      interfaces: Vlan1
  hosts:
    - name: 4.2.2.2-DNS
      ip: 4.2.2.2
    - name: DHCP-Server
      ip: 192.168.3.2
      address_only: true
    - name: Firewall
      ip: 192.168.3.1
      address_only: true
    - name: AWS-East-1
      ip: 50.17.255.254
    - name: Discord
      ip: 162.159.135.232
      url: https://discordapp.com
    - name: Twitch
      ip: 151.101.130.167
      url: https://twitch.tv