
type: leaf

atd_vlan: "1{{ inventory_hostname[-2:] }}"

mgmt_gateway: 192.168.{{ atd_vlan }}.1

csc_cloud_gateway:

    # Daemon Name
  - name: AristaCloudGateway

    # command to run as a daemon
    exec: /usr/bin/acg
    enabled: true
    option: [AGNI_API_TOKEN, "{{ labs[atd_vlan|int]['agni_token'] }}"]

ip_dhcp_snooping:
  enabled: true
  information_option:
    enabled: true
  vlan: 1-200

vlan_interfaces:
  - name: "Vlan{{ atd_vlan }}"
    description: "*** Devices VLAN ***"
    ip_address: "192.168.{{ atd_vlan }}.10/24"
    ip_helpers:
      - ip_helper: 127.0.0.1
      - ip_helper: 192.168.{{ atd_vlan }}.1