
tenants:
  - name: atd_lab
    vrfs:
      - name: default
        svis:

          - id: "{{ atd_vlan|int }}"
            name: TOLA_ATD_{{ atd_vlan }}
            description: "*** ATD LAB VLAN ***"
            ip_address: "192.168.{{ atd_vlan }}.10/24"
            enabled: true
            ip_helpers:
              - ip_helper: 127.0.0.1
              - ip_helper: 192.168.{{ atd_vlan }}.1