---
name: GCP Sync Dev

on:
  workflow_dispatch:
  repository_dispatch:
    types: [guides-dev]

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    concurrency:
      group: doc-build
      cancel-in-progress: true
    name: Build and Deploy Job
    steps:
      - name: checkout files
        uses: actions/checkout@v4
        with:
          ref: guides-dev
          submodules: true

      ###### GCP push portion ######
      - name: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDS }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Use gcloud CLI
        run: 'gcloud info'

      - name: Sync Content to GCP Bucket
        run: gcloud storage rsync . gs://labguides-dev --recursive --checksums-only --exclude="^gha-creds.*$|\.git\/|.gitignore$|.nojekyll$"
