---
name: "Pull Request Testing"

on:
  # Run jobs on any Pull Request activity
  pull_request:

jobs:
  pre_commit:
    name: Run pre-commit validation hooks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - uses: pre-commit/action@v3.0.1

  test_site_build:
    runs-on: ubuntu-latest
    name: Test Build
    needs: [pre_commit ]
    strategy:
      matrix:
        version: [ 2024.1, 2024.2 ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      ##### Test Building Each Version of the Site #####
      - run: |
          pip install -r .devcontainer/requirements.txt
          cd ${{ matrix.version }}
          mkdocs build -s
